version: '3'

services:
  api:
    build: ./api
    image: thepiperpied/ums:beta
    ports:
      - "3001:3001"
    command: ["npm", "run", "start"]
    links: 
      - db
    depends_on:
      - db

  db:
  build: ./db
  image: thepiperpied/ums-db:0.0.1
  ports:
    - "7474:7474"
    - "7687:7687"
  volumes:
    - ./db/data:/data
  command: ["neo4j"]
